### ISSUE TITLE
SMILESLanguage object initiate problem

### ISSUE THREAD

**Issue by cook-kuk** [PaccMann/paccmann_rl#4]
I got the following error, it seems to be an initiation problem with the SMLESLanguage object.

In train_paccmann_rl.py, the smiles language object is created with SMILES Language.load(smiles language path).

When created in this way, we have confirmed that SMLESLanguage does not pass the init function.

So it seems that elements like SMILES Language.special indexes and SMILESLanguage.transform_smiles are not created.

I think the code should be fixed in such a way that the object is first created and then loaded.

Traceback (most recent call last):
  File "C:/Users/seungho.kuk/Desktop/Python_project/paccmann_rl/code/paccmann_generator/examples/train_paccmann_rl.py", line 317, in <module>
    main()
  File "C:/Users/seungho.kuk/Desktop/Python_project/paccmann_rl/code/paccmann_generator/examples/train_paccmann_rl.py", line 223, in main
    cell_line, epoch, params['batch_size']
  File "C:\Users\seungho.kuk\Desktop\Python_project\paccmann_rl\code\paccmann_generator\paccmann_generator\reinforce.py", line 406, in policy_gradient
    latent_z, remove_invalid=True
  File "C:\Users\seungho.kuk\Desktop\Python_project\paccmann_rl\code\paccmann_generator\paccmann_generator\reinforce.py", line 327, in get_smiles_from_latent
    ) for mol_num in iter(mols_numerical)
  File "C:\Users\seungho.kuk\Desktop\Python_project\paccmann_rl\code\paccmann_generator\paccmann_generator\reinforce.py", line 327, in <listcomp>
    ) for mol_num in iter(mols_numerical)
  File "C:\Users\seungho.kuk\Desktop\Python_project\paccmann_rl\code\paccmann_datasets\pytoda\smiles\smiles_language.py", line 637, in token_indexes_to_smiles
    for token_index in token_indexes
  File "C:\Users\seungho.kuk\Desktop\Python_project\paccmann_rl\code\paccmann_datasets\pytoda\smiles\smiles_language.py", line 639, in <listcomp>
    if token_index not in self.special_indexes
AttributeError: 'SMILESLanguage' object has no attribute 'special_indexes'

Process finished with exit code 1

**Comment by drugilsberg** [comment]
Hi @SeunghoKuk-dev, the `special_indexes` attribute has been added in recent versions of `pytoda`. Are you sure you are using a SMILESLanguage object from the right version (a.k.a., 0.0.1)?
Did you use this conda environment (https://github.com/PaccMann/paccmann_rl/blob/master/conda.yml)? I see some absolute path in the stacktrace and I would like to understand what is the setup you are using.

**Comment by cook-kuk** [comment]
thanks， your suggestion has helped me fix this error.
