### ISSUE TITLE
RuntimeError: Expected object of scalar type float but got scalar type __int64 for sequence element 1.

### ISSUE THREAD

**Issue by cook-kuk** [PaccMann/paccmann_rl#6]
During rl model learning, the following errors are found. (I found this error when epoch is 6 epoch.)

As a result of my debugging, it seems to be an error that occurs when a molecule is not created in the generator.generate function when making smile molecules for validation. (mols_numerical is empty tensor.)

How can i fix it?

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/seungho.kuk/Desktop/Python_project/paccmann_rl/code/paccmann_generator/examples/train_paccmann_rl.py", line 313, in <module>
    main()
  File "C:/Users/seungho.kuk/Desktop/Python_project/paccmann_rl/code/paccmann_generator/examples/train_paccmann_rl.py", line 237, in main
    epoch, params['eval_batch_size'], cell_line
  File "C:\Users\seungho.kuk\anaconda3\envs\paccmann_rl_cpu\lib\site-packages\paccmann_generator\reinforce.py", line 280, in generate_compounds_and_evaluate
    latent_z, remove_invalid=True
  File "C:\Users\seungho.kuk\anaconda3\envs\paccmann_rl_cpu\lib\site-packages\paccmann_generator\reinforce.py", line 322, in get_smiles_from_latent
    ) for mol_num in iter(mols_numerical)
  File "C:\Users\seungho.kuk\anaconda3\envs\paccmann_rl_cpu\lib\site-packages\paccmann_generator\reinforce.py", line 322, in <listcomp>
    ) for mol_num in iter(mols_numerical)
RuntimeError: Expected object of scalar type float but got scalar type __int64 for sequence element 1.

**Comment by jannisborn** [comment]
If `mol_numerical` is an empty tensor, it seems that you did not generate any molecules. Since the first epochs all went through, I believe it's not a systematic problem with the package.
